{% set name = "oci" %}
{% set version = "2.137.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oci-{{ version }}.tar.gz
  sha256: 02fe727a4a4ebc5670e51b0caaa2f79d1171f5bfe9eb933ce5fdb845289e0ef1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >70.0.0
  run:
    - python >=3.6
    - certifi
    - cryptography >=3.2.1,<42.0.0
    - pyopenssl >=17.5.0,<24.0.0
    - python-dateutil >=2.5.3,<3.0.0
    - pytz >=2016.10
    - circuitbreaker >=1.3.1,<2.0.0

test:
  imports:
    - oci
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.oracle.com/en-us/iaas/tools/python/latest/index.html
  summary: Oracle Cloud Infrastructure Python SDK
  license: Apache-2.0 OR UPL-1.0
  license_file: LICENSE.txt
  dev_url: https://github.com/oracle/oci-python-sdk

extra:
  recipe-maintainers:
    - manics
