{% set name = "oci" %}
{% set version = "2.158.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oci-{{ version }}.tar.gz
  sha256: c3300bcbfe5549f55a637898a7976499230050a3ae4086d440ae1e5c943f48ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >70.0.0
  run:
    - python >={{ python_min }}
    - certifi
    - cryptography >=3.2.1,<42.0.0
    - pyopenssl >=17.5.0,<24.0.0
    - python-dateutil >=2.5.3,<3.0.0
    - pytz >=2016.10
    - circuitbreaker >=1.3.1,<2.0.0

test:
  imports:
    - oci
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://docs.oracle.com/en-us/iaas/tools/python/latest/index.html
  summary: Oracle Cloud Infrastructure Python SDK
  license: Apache-2.0 OR UPL-1.0
  license_file: LICENSE.txt
  dev_url: https://github.com/oracle/oci-python-sdk

extra:
  recipe-maintainers:
    - manics
